version: "3.8"

services:
  app:
    build: .
    tty: true
    user: 1000:1000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hypedev